name: e2e

on:
  repository_dispatch:
    types: [cluster_image_build_success]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOMAIN: 127.0.0.1.nip.io

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Install sealos
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/labring/ /" | sudo tee /etc/apt/sources.list.d/labring.list
          sudo apt update
          sudo apt install sealos=4.1.4
          sudo sealos version
      - name: Deploy laf
        env:
          DOMAIN: ${{ env.DOMAIN }}
        working-directory: deploy/build
        run: sudo sh install-on-linux.sh $DOMAIN
      - name: Run E2E Test
        run: |
          sudo sh e2e.sh

          
